/* Load this script using conditional IE comments if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'icons-bootstrap\'">' + entity + '</span>' + html;
	}
	var icons = {
			'icon-glass' : '&#xe000;',
			'icon-music' : '&#xe001;',
			'icon-search' : '&#xe002;',
			'icon-envelope' : '&#xe003;',
			'icon-heart' : '&#xe004;',
			'icon-star' : '&#xe005;',
			'icon-star-2' : '&#xe006;',
			'icon-user' : '&#xe007;',
			'icon-film' : '&#xf008;',
			'icon-th-large' : '&#xf009;',
			'icon-th' : '&#xf00a;',
			'icon-th-list' : '&#xf00b;',
			'icon-checkmark' : '&#xe008;',
			'icon-close' : '&#xe009;',
			'icon-zoom-in' : '&#xe00a;',
			'icon-zoom-out' : '&#xe00b;',
			'icon-off' : '&#xf011;',
			'icon-signal' : '&#xf012;',
			'icon-cog' : '&#xe00c;',
			'icon-remove' : '&#xe00d;',
			'icon-home' : '&#x21b8;',
			'icon-file' : '&#xf0d6;',
			'icon-clock' : '&#xe00e;',
			'icon-road' : '&#xe00f;',
			'icon-download' : '&#xe010;',
			'icon-download-2' : '&#xf01a;',
			'icon-upload' : '&#xf01b;',
			'icon-inbox' : '&#xe012;',
			'icon-play' : '&#xe011;',
			'icon-spinner' : '&#xe013;',
			'icon-loop' : '&#xe014;',
			'icon-list-alt' : '&#xf022;',
			'icon-lock' : '&#xe015;',
			'icon-flag' : '&#xe016;',
			'icon-headphones' : '&#xe017;',
			'icon-volume-mute' : '&#xe018;',
			'icon-volume-low' : '&#xe019;',
			'icon-volume-medium' : '&#xe01a;',
			'icon-qrcode' : '&#xe01b;',
			'icon-barcode' : '&#xe01c;',
			'icon-tag' : '&#xf02b;',
			'icon-tags' : '&#xf02c;',
			'icon-book' : '&#xe01d;',
			'icon-bookmark' : '&#xe01e;',
			'icon-print' : '&#xf02f;',
			'icon-camera' : '&#xf030;',
			'icon-font' : '&#xf031;',
			'icon-bold' : '&#xe01f;',
			'icon-italic' : '&#xe020;',
			'icon-text-height' : '&#xe021;',
			'icon-text-width' : '&#xe022;',
			'icon-align-left' : '&#xf036;',
			'icon-align-center' : '&#xf037;',
			'icon-align-right' : '&#xf038;',
			'icon-align-justify' : '&#xf039;',
			'icon-list' : '&#xf03a;',
			'icon-indentleft' : '&#xf1f2;',
			'icon-indentright' : '&#xf1f3;',
			'icon-facetime-video' : '&#xf03d;',
			'icon-image' : '&#xe023;',
			'icon-pencil' : '&#xe024;',
			'icon-location' : '&#xe025;',
			'icon-adjust' : '&#xf042;',
			'icon-tint' : '&#xf043;',
			'icon-edit' : '&#xf044;',
			'icon-share' : '&#xf045;',
			'icon-check' : '&#xf046;',
			'icon-move' : '&#xf047;',
			'icon-step-backward' : '&#xf048;',
			'icon-fast-backward' : '&#xf049;',
			'icon-backward' : '&#xf04a;',
			'icon-play-2' : '&#xf04b;',
			'icon-pause' : '&#xf04c;',
			'icon-stop' : '&#xf04d;',
			'icon-forward' : '&#xf04e;',
			'icon-fast-forward' : '&#xf050;',
			'icon-step-forward' : '&#xf051;',
			'icon-eject' : '&#xf052;',
			'icon-chevron-left' : '&#xf053;',
			'icon-chevron-right' : '&#xf054;',
			'icon-plus-sign' : '&#xf055;',
			'icon-minus-sign' : '&#xf056;',
			'icon-remove-sign' : '&#xf057;',
			'icon-ok-sign' : '&#xf058;',
			'icon-question-sign' : '&#xf059;',
			'icon-info-sign' : '&#xf05a;',
			'icon-screenshot' : '&#xf05b;',
			'icon-remove-circle' : '&#xf05c;',
			'icon-ok-circle' : '&#xf05d;',
			'icon-ban-circle' : '&#xf05e;',
			'icon-arrow-left' : '&#xf060;',
			'icon-arrow-right' : '&#xf061;',
			'icon-arrow-up' : '&#xf062;',
			'icon-arrow-down' : '&#xf063;',
			'icon-share-alt' : '&#xf064;',
			'icon-resize-full' : '&#xf065;',
			'icon-resize-small' : '&#xf066;',
			'icon-plus' : '&#xf067;',
			'icon-minus' : '&#xf068;',
			'icon-asterisk' : '&#xf069;',
			'icon-exclamation-sign' : '&#xf06a;',
			'icon-gift' : '&#xf06b;',
			'icon-leaf' : '&#xf06c;',
			'icon-fire' : '&#xe026;',
			'icon-eye' : '&#xe027;',
			'icon-eye-blocked' : '&#xe028;',
			'icon-warning' : '&#xe029;',
			'icon-airplane' : '&#xe02a;',
			'icon-calendar' : '&#xe02b;',
			'icon-shuffle' : '&#xe02c;',
			'icon-bubble' : '&#xe02d;',
			'icon-magnet' : '&#xf076;',
			'icon-chevron-up' : '&#xf077;',
			'icon-chevron-down' : '&#xf078;',
			'icon-retweet' : '&#xf079;',
			'icon-cart' : '&#xe02e;',
			'icon-folder' : '&#xe02f;',
			'icon-folder-open' : '&#xe030;',
			'icon-resize-vertical' : '&#xf07d;',
			'icon-resize-horizontal' : '&#xf07e;',
			'icon-storage' : '&#xe031;',
			'icon-bullhorn' : '&#xe032;',
			'icon-bell' : '&#xe033;',
			'icon-certificate' : '&#xf0a3;',
			'icon-thumbs-up' : '&#xf087;',
			'icon-thumbs-down' : '&#xf088;',
			'icon-hand-right' : '&#xf0a4;',
			'icon-hand-left' : '&#xf0a5;',
			'icon-hand-up' : '&#xf0a6;',
			'icon-hand-down' : '&#xf0a7;',
			'icon-arrow-right-alt1' : '&#xe034;',
			'icon-arrow-left-alt1' : '&#xe035;',
			'icon-arrow-up-alt1' : '&#xe036;',
			'icon-arrow-down-alt1' : '&#xe037;',
			'icon-earth' : '&#xe038;',
			'icon-wrench' : '&#xf0ad;',
			'icon-tasks' : '&#xf0ae;',
			'icon-filter' : '&#xe039;',
			'icon-briefcase' : '&#xe03a;',
			'icon-expand' : '&#xe03b;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};